-- STEP 1: INFRASTRUCTURE
CREATE DATABASE IF NOT EXISTS CRYPTO_PROJECT;
CREATE SCHEMA IF NOT EXISTS CRYPTO_PROJECT.STAR_SCHEMA;
USE SCHEMA CRYPTO_PROJECT.STAR_SCHEMA;

-- STEP 2: DIMENSIONS
CREATE TABLE IF NOT EXISTS DIM_TIME (
    TIME_ID TIMESTAMP_NTZ PRIMARY KEY, 
    DAY INT, MONTH INT, YEAR INT, QUARTER INT, HOUR INT, MINUTE INT, SECOND INT
);

CREATE TABLE IF NOT EXISTS DIM_PAIR (
    PAIR_ID INT PRIMARY KEY,
    PAIR_NAME VARCHAR(20),
    CATEGORY_NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS DIM_SOURCE (
    SOURCE_ID INT PRIMARY KEY,
    SOURCE_NAME VARCHAR(50)
);

-- STEP 3: FACT TABLE 
CREATE TABLE IF NOT EXISTS FACT_PRICE (
    TIME_ID TIMESTAMP_NTZ,
    PAIR_ID INT,
    SOURCE_ID INT,
    PRICE DECIMAL(20, 8),
    CONSTRAINT fk_time FOREIGN KEY (TIME_ID) REFERENCES DIM_TIME(TIME_ID),
    CONSTRAINT fk_pair FOREIGN KEY (PAIR_ID) REFERENCES DIM_PAIR(PAIR_ID),
    CONSTRAINT fk_source FOREIGN KEY (SOURCE_ID) REFERENCES DIM_SOURCE(SOURCE_ID)
);

-- STEP 4: INITIAL DATA
INSERT INTO DIM_SOURCE (SOURCE_ID, SOURCE_NAME) VALUES (1, 'Binance') ON CONFLICT DO NOTHING;

-- STEP 5: ANALYTICS VIEW 
CREATE OR REPLACE VIEW V_CATEGORY_PERFORMANCE AS
SELECT 
    p.PAIR_NAME, 
    f.PRICE, 
    p.CATEGORY_NAME,
    t.DAY, t.MONTH, t.YEAR, t.TIME_ID
FROM FACT_PRICE f
JOIN DIM_PAIR p ON f.PAIR_ID = p.PAIR_ID
JOIN DIM_TIME t ON f.TIME_ID = t.TIME_ID;