CREATE DATABASE IF NOT EXISTS CryptoBot_Step2;
USE CryptoBot_Step2;

CREATE TABLE IF NOT EXISTS Currency (
    Currency_ID INT AUTO_INCREMENT PRIMARY KEY,
    Currency_Name VARCHAR(50) NOT NULL UNIQUE,
    Asset_Type VARCHAR(20) DEFAULT 'Crypto',
    Category VARCHAR(50) DEFAULT 'To be defined'
);

CREATE TABLE IF NOT EXISTS Pair (
    Pair_ID INT AUTO_INCREMENT PRIMARY KEY,
    Pair_Name VARCHAR(20) NOT NULL UNIQUE,
    Currency_ID INT,
    FOREIGN KEY (Currency_ID) REFERENCES Currency(Currency_ID)
);

CREATE TABLE IF NOT EXISTS Price_Hist (
    Price_ID INT AUTO_INCREMENT PRIMARY KEY,
    Pair_ID INT,
    Price DECIMAL(20, 8) NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Pair_ID) REFERENCES Pair(Pair_ID)
);